version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: laravel-amqp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-amqp-php
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      XDEBUG_MODE: "off"
      INTEGRATION_TESTS: "0"
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: guest
      AMQP_PASSWORD: guest
      AMQP_VHOST: /
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: bash -lc "composer install && tail -f /dev/null"

